FROM python:3.12-slim

WORKDIR /app

COPY ./devops/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/api/ /app/api/
COPY ./src/data /app/api/data
COPY ./src/utilities /app/api/utilities

WORKDIR /app/api
EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi"]