"""kafka init

Revision ID: 192cbf7609fb
Revises: 
Create Date: 2025-10-13 09:48:33.491238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192cbf7609fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_data_address'), 'pii_data', ['address'], unique=False)
    op.create_index(op.f('ix_pii_data_email'), 'pii_data', ['email'], unique=True)
    op.create_index(op.f('ix_pii_data_id'), 'pii_data', ['id'], unique=False)
    op.create_index(op.f('ix_pii_data_name'), 'pii_data', ['name'], unique=False)
    op.create_index(op.f('ix_pii_data_phone_number'), 'pii_data', ['phone_number'], unique=True)
    op.drop_table('knicks')
    op.drop_table('polars_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polars_test',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('knicks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('jersey_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('college', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='knicks_pkey')
    )
    op.drop_index(op.f('ix_pii_data_phone_number'), table_name='pii_data')
    op.drop_index(op.f('ix_pii_data_name'), table_name='pii_data')
    op.drop_index(op.f('ix_pii_data_id'), table_name='pii_data')
    op.drop_index(op.f('ix_pii_data_email'), table_name='pii_data')
    op.drop_index(op.f('ix_pii_data_address'), table_name='pii_data')
    op.drop_table('pii_data')
    # ### end Alembic commands ###
