"""add normalized table

Revision ID: 2085e293e134
Revises: 80bb8351d948
Create Date: 2025-10-13 14:28:27.317194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2085e293e134"
down_revision: Union[str, None] = "80bb8351d948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "normalized_pii_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("address_line_1", sa.String(), nullable=True),
        sa.Column("address_line_2", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("zip_code", sa.String(), nullable=True),
        sa.Column("zip_plus_4", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("phone_extension", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("normalized_at", sa.DateTime(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["pii_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(
        op.f("ix_normalized_pii_data_id"), "normalized_pii_data", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_normalized_pii_data_source_id"),
        "normalized_pii_data",
        ["source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_normalized_pii_data_source_id"), table_name="normalized_pii_data"
    )
    op.drop_index(op.f("ix_normalized_pii_data_id"), table_name="normalized_pii_data")
    op.drop_table("normalized_pii_data")
    # ### end Alembic commands ###
