"""remove normalized constraints

Revision ID: 4c122000eb5c
Revises: ed6ca8150315
Create Date: 2025-10-17 21:39:02.659913

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c122000eb5c"
down_revision: Union[str, None] = "ed6ca8150315"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "normalized_pii_data_email_key", "normalized_pii_data", type_="unique"
    )
    op.drop_constraint(
        "normalized_pii_data_phone_number_key", "normalized_pii_data", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "normalized_pii_data_phone_number_key",
        "normalized_pii_data",
        ["phone_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        "normalized_pii_data_email_key",
        "normalized_pii_data",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
