"""drop email constraint

Revision ID: 532cf167b18f
Revises: 4c122000eb5c
Create Date: 2025-10-20 21:42:30.004950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532cf167b18f'
down_revision: Union[str, None] = '4c122000eb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pii_data_email_key'), 'pii_data', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('pii_data_email_key'), 'pii_data', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
