"""add linkage table

Revision ID: 80bb8351d948
Revises: 192cbf7609fb
Create Date: 2025-10-13 13:55:02.835310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bb8351d948'
down_revision: Union[str, None] = '192cbf7609fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pii_data.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['pii_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkage_id'), 'linkage', ['id'], unique=False)
    op.create_index(op.f('ix_linkage_match_id'), 'linkage', ['match_id'], unique=False)
    op.add_column('pii_data', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pii_data', 'created_at')
    op.drop_index(op.f('ix_linkage_match_id'), table_name='linkage')
    op.drop_index(op.f('ix_linkage_id'), table_name='linkage')
    op.drop_table('linkage')
    # ### end Alembic commands ###
