"""remove pii indices

Revision ID: ed6ca8150315
Revises: 2085e293e134
Create Date: 2025-10-17 21:37:30.499465

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed6ca8150315"
down_revision: Union[str, None] = "2085e293e134"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pii_data_address", table_name="pii_data")
    op.drop_index("ix_pii_data_email", table_name="pii_data")
    op.drop_index("ix_pii_data_name", table_name="pii_data")
    op.drop_index("ix_pii_data_phone_number", table_name="pii_data")
    op.create_unique_constraint(None, "pii_data", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pii_data", type_="unique")
    op.create_index(
        "ix_pii_data_phone_number", "pii_data", ["phone_number"], unique=True
    )
    op.create_index("ix_pii_data_name", "pii_data", ["name"], unique=False)
    op.create_index("ix_pii_data_email", "pii_data", ["email"], unique=True)
    op.create_index("ix_pii_data_address", "pii_data", ["address"], unique=False)
    # ### end Alembic commands ###
